#+TITLE: About
#+HUGO_BASE_DIR: ../
#+HUGO_LAYOUT: page
#+DATE: 2025-10-13
#+HUGO_PUBLISHDATE: 2025-10-13
#+HUGO_DRAFT: false
#+HUGO_SECTION: .
#+AUTHOR: TRNEEDANAME
#+macro: relref @@hugo:[@@ $1 @@hugo:]({{< relref "$2" >}})@@
#+HUGO_CUSTOM_FRONT_MATTER: :ShowToc false ShowBreadCrumbs: false :ShowPostNavLinks false

** Who I am

Hi :wave: !

I'm TRNEEDANAME, a french game dev / mod maker.
This site is my blog, where you'll find what I did and what I'm doing.

*** What I use

I use Linux as my main OS (NixOS to be precise), before that I used Arch for close to 4 years.

As my text editor / IDE / everything else (mostly), I use [[https://www.gnu.org/software/emacs/emacs.html][Emacs]] because I write in org-mode (I use a framework called [[https://github.com/doomemacs/doomemacs][Doom Emacs]]).

The file you're reading is in fact a ~.org~ file !

*** What I do

I make mods for [[https://projectzomboid.com/blog/][Project Zomboid]] and [[https://xcom.com][Xcom]] in my spare time, I started with Xcom 2 in ~2020, in 2024 I joined the Project Zomboid RP scene as a player, then admin / mod maker for different servers.

I also play games, as of now I'm playing +Satisfactory+ Factorio (it took over my life) and Project Zomboid.

I enjoy writing wikis, as shown by my [[https://github.com/TRNEEDANAME/Militia_Wiki/wiki][Militia wiki]] for Xcom 2 (still in the work as of now)

Outside of things computer related, I do archery.

*** Technology used by this site

The theme used is [[https://github.com/adityatelange/hugo-PaperMod][PaperMod]] with a nord inspired theme.

This site is made using [[https://gohugo.io/][Hugo]] with [[https://ox-hugo.scripter.co/][ox-hugo]] to convert from ~.org~ file to ~.md~

**** The fonts used

- Titles : Noto Sans Display
- Main body text : Noto Sans
- Code / monospace : Berkely-Mono (with ligatures)

The fonts are local as to allow for faster load time.

** Contact me

To contact me about this website, please send me an email to [[mailto:trneedaname@proton.me][trneedaname@proton.me]]. Otherwise please fill a bug / feature report on the github repository of the mod / steam page.

** Licences

All the content on this site (unless otherwise specified) is under GNU GPLv3 licence, all of the code is under the same licence.

My mods / content will never be behind a paywall, as this go against the core idea of programming for me, they will always be under MIT License.
